version: '3.8'

services:
  nginx:
    restart: always
    ports:
      - "17080:80"
      - "17443:443"
    volumes:
      - ./frontend/dist:/var/www/frontend/dist:ro
      - ./docker/nginx/conf.d/prod:/etc/nginx/conf.d:ro

  php:
    restart: always
    environment:
      - APP_ENV=prod

  mysql:
    restart: always

  redis:
    restart: always

  kafka:
    restart: always
    ports:
      - "17092:9092"

  zookeeper:
    restart: always
