framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: true
    handle_all_throwables: true

    session:
        handler_id: '%env(REDIS_DSN)%'
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'

    rate_limiter:
        auth_login:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
        auth_register:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
        auth_refresh:
            policy: sliding_window
            limit: 10
            interval: '1 minute'
        user_master_password:
            policy: sliding_window
            limit: 3
            interval: '1 hour'
        auth_2fa_verify:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'
        auth_resend_verification:
            policy: sliding_window
            limit: 3
            interval: '1 hour'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
