monolog:
  handlers:
    main:
      type: stream
      path: "php://stderr"
      level: debug
      channels: ["!event"]
    exception:
      type: stream
      path: "php://stderr"
      level: error
